//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Belinskiy.NeuroNet
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class NeuronNetwork
	{
		private NeuronLayer inputLayer
		{
			get;
			set;
		}

		private NeuronLayer outputLayer
		{
			get;
			set;
		}

		private List<NeuronLayer> hiddenLayers
		{
			get;
			set;
		}

		private List<double> signal
		{
			get;
			set;
		}

		public virtual void SetSignal(List<double> inputSignal)
		{
			throw new System.NotImplementedException();
		}

		public virtual List<double> GetSignal()
		{
			throw new System.NotImplementedException();
		}

	}
}

