//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Belinskiy.NeuroNet
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public abstract class NeuroNetworkConstructor
	{
	}
}

