//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан инструментальным средством
//     В случае повторного создания кода изменения, внесенные в этот файл, будут потеряны.
// </auto-generated>
//------------------------------------------------------------------------------
namespace Belinskiy.NeuroNet
{
	using System;
	using System.Collections.Generic;
	using System.Linq;
	using System.Text;

	public class Synapse
	{
		private double weight
		{
			get;
			set;
		}

		private Neuron From
		{
			get;
			set;
		}

		private Neuron To
		{
			get;
			set;
		}

		private double signal
		{
			get;
			set;
		}

		public virtual void SetSignal(double inputSignal)
		{
			throw new System.NotImplementedException();
		}

		public virtual double GetSignal()
		{
			throw new System.NotImplementedException();
		}

	}
}

